---
title: "Vision Zero - Testing"
format: pdf
editor: visual
---

#### Packages:

```{r}
library(sf)
library(ggplot2)
library(dplyr)
library(jsonlite)
library(lwgeom)
library(readxl)
library(scales)

library(zoo)
```

## Loading and Cleaning Data

Loading dataframes (GeoJSON Format)

```{r}
#| echo: false
#| message: false
#| warning: false
#| output: false

strassen_wege <- st_read("strassen_wege.geojson")
velorouten <- st_read("velorouten.geojson")
unfaelle <- st_read("unfaelle.geojson")

velostadtplan <- st_read("velostadtplan.geojson")
```

#### Cleaning "velostrassen"

```{r}
velostrassen <- velostadtplan %>% filter(gml_id == "Velostrasse")
```

```{r}
velostrassen_union <- velostrassen %>%
  st_union() %>%
  st_line_merge()

# Schritt 2: Wieder aufteilen in einzelne Linien
velostrassen_cleaned <- st_cast(velostrassen_union, "LINESTRING") %>%
  st_as_sf() %>%
  mutate(temp_ID = paste0(row_number()))

```

Clean copies

```{r fig.width=8, fig.height=6}
velostrassen_cleaned_selection <- velostrassen_cleaned %>% filter(temp_ID %in% c(1, 3, 5, 6, 9, 11, 13, 17, 21, 22, 23, 29, 39, 45, 54, 58, 41, 30 , 37, 34, 43, 23, 56, 47, 49, 51, 26))

p <- ggplot() +
  geom_sf(data = strassen_wege, color = "grey", size = 1, alpha = 0.5) +
  geom_sf(data = velostrassen_cleaned_selection, aes(color = temp_ID), size = 1, alpha = 0.3) +
  geom_sf_text(data = velostrassen_cleaned_selection, aes(label = temp_ID), size = 1, color = "black", check_overlap = FALSE) +
  theme_void() +
  theme(legend.position = "none")

print(p)

ggsave("velorouten_grouped_selection.jpeg", plot = p, width = 12, height = 8, dpi = 600)

remove(velostrassen_cleaned, velostrassen_union)
```

#### Combine with "unfaelle" Dataset

```{r}
# Sicherheitscheck: gleiche CRS (Koordinatensystem)
unfaelle <- st_transform(unfaelle, st_crs(velostrassen_cleaned_selection))

# Optional: etwas Toleranzradius, falls Punkte nicht exakt auf Linie liegen (z.B. 10 Meter)
buffered_velo <- st_buffer(velostrassen_cleaned_selection, dist = 15)

# Räumlicher Join
unfaelle_with_match <- st_join(unfaelle, buffered_velo["temp_ID"])

# Neue Variable: TRUE/FALSE
unfaelle_with_match <- unfaelle_with_match %>%
  mutate(
    on_velostrasse = !is.na(temp_ID)  # TRUE wenn er zugewiesen wurde
  )
```

```{r}
p <- ggplot() +
  geom_sf(data = strassen_wege, color = "grey", size = 1, alpha = 0.5) +
  geom_sf(data = velostrassen_cleaned_selection, aes(color = temp_ID), size = 1, alpha = 0.3) +
  geom_sf(data = unfaelle_with_match, aes(color = temp_ID), size = 0.1, alpha = 0.5) +
  theme_void() +
  theme(legend.position = "none")

print(p)

ggsave("accident_matching.jpeg", plot = p, width = 12, height = 8, dpi = 600)
```

#### Add street name

```{r}
velostrassen_ID_sheet <- read_excel("velostrassen_ID_sheet.xlsx")

unfaelle_with_match$temp_ID <- as.numeric(unfaelle_with_match$temp_ID)

# left-join
unfaelle_clean <- unfaelle_with_match %>%
  left_join(velostrassen_ID_sheet, by = "temp_ID")

table(unfaelle_clean$name)
```

#### Backtrack Implementation

```{r}
unfaelle_clean <- unfaelle_clean %>%
  mutate(
    date_accident = as.Date(paste0(jahr, "-", monat, "-01")),
    ym_accident = as.yearmon(date_accident))


unfaelle_clean_velostrasse <- unfaelle_clean %>%
  filter(on_velostrasse == TRUE) %>%
  mutate(date_reference = as.Date(paste0(year, "-", month, "-01")),
    ym_reference = as.yearmon(date_reference),
    diff = ym_accident - ym_reference,
    diff_months = round((ym_accident - ym_reference) * 12))

```

## Plotting Data

```{r}
table(unfaelle_clean_velostrasse$diff_months)
```

```{r}
p <- unfaelle_clean_velostrasse %>%
  filter(on_velostrasse == TRUE) %>%
ggplot(aes(diff_months)) +
  geom_histogram(binwidth = 12, fill = "pink", color = "grey30") +
  geom_vline(xintercept = 0, color = "red", linetype = 1, size = 0.5) +
  geom_text(aes(x = 10, y = 20, label = "Velostreet transition"), 
            vjust = -1, hjust = 1.2, color = "red", size = 4) +
  scale_x_continuous(breaks = seq(floor(min(unfaelle_clean_velostrasse$diff_months) / 12) * 12,
                                  ceiling(max(unfaelle_clean_velostrasse$diff_months) / 12) *
                                    12, 
                                  by = 12)) +
  xlab("Months relative to velostreet transition") +
  ylab("Amount of Accidents") +
  theme_minimal()

print(p)

ggsave("Plot_1.jpeg", plot = p, width = 12, height = 8, dpi = 600)
```

```{r}
p <- unfaelle_clean_velostrasse %>%
  group_by(diff_months, name) %>%
  summarise(count = n()) %>%
ggplot(aes(diff_months, count)) +
  geom_point(aes(color = name)) +
  geom_smooth() +
  geom_vline(xintercept = 0, color = "red", linetype = 1, size = 0.5) +
  geom_text(aes(x = 10, y = 4, label = "Velostreet transition"), 
            vjust = -1, hjust = 1.2, color = "red", size = 4) +
  scale_x_continuous(breaks = seq(floor(min(unfaelle_clean_velostrasse$diff_months) / 12) * 12, 
                 ceiling(max(unfaelle_clean_velostrasse$diff_months) / 12) * 12, 
                 by = 12)) +
  xlab("Months relative to velostreet transition") +
  ylab("Amount of Accidents") +
  theme_minimal()

print(p)

ggsave("Plot_1.1.jpeg", plot = p, width = 12, height = 8, dpi = 600)
```

```{r}
p <- unfaelle_clean_velostrasse %>%
  filter(diff_months >= -60 & diff_months <= 24) %>%
  mutate(diff_months_group = floor(diff_months / 3) * 3) %>%   
  group_by(diff_months_group) %>%
  summarise(count = n(), .groups = "drop") %>%
  mutate(after_transition = diff_months_group >= 0) %>%
  ggplot(aes(diff_months_group, count)) +
  geom_point() +
  geom_smooth(aes(group = after_transition), method = "lm") +
  geom_vline(xintercept = 0, color = "red", linetype = 1, size = 0.5) +
  geom_text(aes(x = 10, y = 7, label = "Velostreet transition"), 
            vjust = -1, hjust = 1.2, color = "red", size = 4) +
  scale_x_continuous(
    breaks = seq(
      floor(min(unfaelle_clean_velostrasse$diff_months) / 12) * 12,
      ceiling(max(unfaelle_clean_velostrasse$diff_months) / 12) * 12,
      by = 12
    )
  ) +
  ggtitle("Amount of accidents across all velostrassen (before and after transition)") +
  xlab("Months relative to velostreet transition (binned by 3)") +
  ylab("Amount of Accidents across all velostrassen") +
  theme_minimal()

print(p)

ggsave("Plot_1.2.jpeg", plot = p, width = 12, height = 8, dpi = 600)
```

```{r}
ggplot(unfaelle_clean, aes(date_accident)) +
  geom_histogram()

unfaelle_clean %>%
  filter(fahrrd_bet == "true") %>%
  ggplot(aes(date_accident)) +
  geom_histogram() +
  scale_x_date(
    breaks = seq(from = min(unfaelle_clean$date_accident), 
                 to = max(unfaelle_clean$date_accident), 
                 by = "2 years"),  # Set breaks every 2 years
    date_labels = "%Y"  # Format the labels as years
)
```

```{r}

p <- unfaelle_clean %>%
  group_by(date_accident) %>%
  summarise(relative_ov = sum(on_velostrasse == TRUE) / n()) %>%
ggplot(aes(date_accident, relative_ov)) +
  geom_point() +
  geom_smooth() +
  geom_vline(xintercept = as.Date("2021-04-01"), color = "red", linetype = "dashed", size = 0.5) +
  geom_text(aes(x = as.Date("2021-04-01"), y = 0.1, label = "Estimated average year of implementation"), color = "red", vjust = -0.5, hjust = 0.5, size = 3) +
  scale_x_date(
    breaks = seq(from = min(unfaelle_clean$date_accident), 
                 to = max(unfaelle_clean$date_accident), 
                 by = "2 years"),  # Set breaks every 2 years
    date_labels = "%Y"  # Format the labels as years
) +
  scale_y_continuous(labels = scales::percent) +
  ggtitle("Proportion of accidents on velostrassen (before and after implementation)") +
  xlab("") +
  ylab("") +
  theme_minimal()

print(p)

ggsave("Plot_2.jpeg", plot = p, width = 12, height = 8, dpi = 600)
```

## Traffic count data

Underlying question: Is the increase in accidents due to more cyclists around Basel?

```{r}
zaehlung <- read.csv2("zaehlung.csv")
```

```{r}
table(zaehlung$SiteName, zaehlung$Year)
```

```{r}
zaehlung <- zaehlung %>%
  mutate(ym = as.yearmon(paste0(Year, "-", Month)))

# Sites mit mehr als 1 Messung im Jahr 2011 auswählen
sites_with_multiple_measurements <- zaehlung %>%
  filter(Year == 2011) %>%
  group_by(SiteName) %>%
  summarise(count = n()) %>%
  filter(count > 1) %>%
  pull(SiteName)

# Gesamten Datensatz auf diese Sites filtern
zaehlung_since_2011 <- zaehlung %>%
  filter(SiteName %in% sites_with_multiple_measurements)

```

```{r}
p <- zaehlung_since_2011 %>%
  filter(TrafficType == "Velo") %>%
  group_by(ym, SiteName) %>%
  summarise(Total_per_Street = sum(Total)) %>%
ggplot(aes(ym, Total_per_Street, group = SiteName, color = SiteName)) +
  geom_point() +
  geom_smooth()

ggsave("Plot_3.jpeg", plot = p, width = 20, height = 8, dpi = 600)

print(p)
```

```{r}
zaehlung_selection <- zaehlung_since_2011 %>%
  filter(!(SiteCode %in% c(659, 660)))

table(zaehlung_selection$SiteName, zaehlung_selection$Year)
```

```{r}
p <- zaehlung_selection %>%
  filter(TrafficType == "Velo") %>%
  group_by(ym, SiteName) %>%
  summarise(Total_per_Meassurement = sum(Total) / n()) %>%
ggplot(aes(ym, mean_Total_per_Meassure_across_all)) +
  geom_point() +
  geom_smooth()

ggsave("Plot_4.jpeg", plot = p, width = 20, height = 8, dpi = 600)
```



## Old Plots

```{r fig.width=8, fig.height=6}
ggplot() +
  geom_sf(data = strassen_wege, color = "grey", size = 1, alpha = 0.5) +
  geom_sf(data = strassen_wege_hvs, color = "purple", size = 10, alpha = 0.3) +
  geom_sf(data = velorouten, color = "darkgreen", size = 10, alpha = 0.3) +
  geom_sf(data = unfaelle_velo_23, color = "red", size = 0.1) +
  theme_void() +
  labs(title = "Comparison of Veloroutes and Mainstreet (Accidents 2023)") +
  theme(legend.position = "none")

print(p)
```

```{r}
unfaelle_velo_1 <- unfaelle %>% filter(fahrrd_bet == "true" & jahr < 2017)
unfaelle_velo_2 <- unfaelle %>% filter(fahrrd_bet == "true" & jahr >= 2017)

plot <- ggplot() +
  geom_sf(data = strassen_wege, color = "grey", size = 1, alpha = 0.5) +
  geom_sf(data = unfaelle_velo_1, color = "red", size = 0.1) +
  geom_sf(data = unfaelle_velo_2, color = "green", size = 0.1) +
  theme_void() +
  labs(title = "Comparison of Veloroutes and Mainstreet") +
  theme(legend.position = "none")

ggsave("velorouten_plot_highres.jpeg", plot = plot, width = 12, height = 8, dpi = 300)
```
